services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    env_file:
      - .env
    environment:
      - QUEUE_BULL_REDIS_HOST=redis-server
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_PASSWORD=
      - QUEUE_BULL_REDIS_USERNAME=
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis
      - postgres

  n8n-worker-1:
    image: n8nio/n8n
    env_file:
      - .env
    environment:
    - QUEUE_BULL_REDIS_HOST=redis-server
    - QUEUE_BULL_REDIS_PORT=6379
    - QUEUE_BULL_REDIS_DB=0
    - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_PASSWORD=
    - QUEUE_BULL_REDIS_USERNAME=
    - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    - N8N_RUNNERS_ENABLED=true
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    command: worker
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - n8n

  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    image: ankane/pgvector:latest   # Postgres com pgvector já incluso
    container_name: postgres_pgvector
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    ports:
      - "9090:8080"
    env_file:
      - .env

    depends_on:
      - redis
      - postgres

    environment:

      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis-server:6379/1
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
    volumes:
      - evolution_instances:/evolution/instances
volumes:
  n8n_data:
  redis_data:
  evolution_instances:
